spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa?characterEncoding=utf8&useSSL=true
    username: smelt
    password: smelt@jingnuo#2018
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update